// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmZfpexyKgb7c8eiXxkA-W_JU3WbjHSiw',
    appId: '1:47611700680:web:05a3e72293d2117fa10cfd',
    messagingSenderId: '47611700680',
    projectId: 'meetly-fea92',
    authDomain: 'meetly-fea92.firebaseapp.com',
    storageBucket: 'meetly-fea92.firebasestorage.app',
    measurementId: 'G-KBK8JKN0N1',
    databaseURL: 'https://meetly-fea92-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc3MR07Oz7ZvYh3GYjXthXs_kxWEGWinU',
    appId: '1:47611700680:android:03379720e870855ba10cfd',
    messagingSenderId: '47611700680',
    projectId: 'meetly-fea92',
    storageBucket: 'meetly-fea92.firebasestorage.app',
    databaseURL: 'https://meetly-fea92-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0QqO6EKtlwrYOQTtQmCyRZKw1G217PVw',
    appId: '1:47611700680:ios:6c4f939f12388254a10cfd',
    messagingSenderId: '47611700680',
    projectId: 'meetly-fea92',
    storageBucket: 'meetly-fea92.firebasestorage.app',
    iosBundleId: 'com.meetly.meetly',
    databaseURL: 'https://meetly-fea92-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0QqO6EKtlwrYOQTtQmCyRZKw1G217PVw',
    appId: '1:47611700680:ios:6c4f939f12388254a10cfd',
    messagingSenderId: '47611700680',
    projectId: 'meetly-fea92',
    storageBucket: 'meetly-fea92.firebasestorage.app',
    iosBundleId: 'com.meetly.meetly',
    databaseURL: 'https://meetly-fea92-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmZfpexyKgb7c8eiXxkA-W_JU3WbjHSiw',
    appId: '1:47611700680:web:823221226b11fb77a10cfd',
    messagingSenderId: '47611700680',
    projectId: 'meetly-fea92',
    authDomain: 'meetly-fea92.firebaseapp.com',
    storageBucket: 'meetly-fea92.firebasestorage.app',
    measurementId: 'G-KLSG2VMQ2B',
    databaseURL: 'https://meetly-fea92-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
